### ISSUE TITLE
Gå gjennom quickstart Azure API (ressurs i discord)

### ISSUE THREAD

**Issue by gsvartsund** [kartAI/NGIS-training-machine-webclient#13]

**Comment by gsvartsund** [comment]
https://portal.azure.com/#view/Microsoft_Azure_Resources/QuickstartCenterBlade

**Comment by Thyrgils** [comment]
Jeg (Tørres) har gått igjennom denne 01.02.2024, tok med ca. 2 timer

**Comment by gsvartsund** [comment]
Alle gjort den. 2 timer per pers = 10 timer.
