### ISSUE TITLE
Rapportskriving - Sprint 1

### ISSUE THREAD

**Issue by victbakk** [kartAI/NGIS-training-machine-webclient#14]

**Comment by victbakk** [comment]
Første utkast av påbegynnelse, gjerne sjekk det ut

**Comment by gsvartsund** [comment]
La til litt, føler den ser bra ut nå?

**Comment by gsvartsund** [comment]
så på den enda mer, og skrev den litt mer strukturert. Brukte ca. 1 time. på dette.

**Comment by Thyrgils** [comment]
Ser fint ut som førsteutkast.
denne brukte vi totalt 3 timer på
