### ISSUE TITLE
WMS (BUGFIX) - Skrive funksjon som konverterer til riktig BBOX uavhengig av hvor man starter

### ISSUE THREAD

**Issue by springvalley** [kartAI/NGIS-training-machine-webclient#158]

**Comment by springvalley** [comment]
Usikker på hvordan applikasjonen fungerer hvis man ikke tegner firkant fra øvre venstre til nedre høyre hjørne, dette må evt undersøkes og fikses

**Comment by victbakk** [comment]
Dette skal funke greit
