### ISSUE TITLE
WMS (BUGFIX) - Håndtere koordinater som ikke er kvadrater

### ISSUE THREAD

**Issue by springvalley** [kartAI/NGIS-training-machine-webclient#159]

**Comment by springvalley** [comment]
Koordinater som ikke er kvadrater blir i dag et strekt ut bilde i WMSen, ser for meg at dette ikke er ønskelig. Ser for meg at vi må lage en funksjon som bryter ned koordinatene sånn at vi får kvadrater også gjøre flere kall til WMSen.

**Comment by victbakk** [comment]
Fikset ved bruk av tile system
