### ISSUE TITLE
Oppdatere sanderscript med relevant kode fra sanderscript 2

### ISSUE THREAD

**Issue by victbakk** [kartAI/NGIS-training-machine-webclient#202]

**Comment by victbakk** [comment]
Var litt å sette seg inn i, putter den tilbake i gjøremål så noen andre/jeg kan komme tilbake til den

**Comment by springvalley** [comment]
Brukte rundt 5 timer totalt på å sette meg inn i/implementere, @victbakk hvor mye tid brukte du?

**Comment by victbakk** [comment]
Brukte 3 timer på å forsøke implementering. Det blir da 8 timer totalt.
