### ISSUE TITLE
Finne ut hvordan vi skal lagre koordinater og config i cookies/session

### ISSUE THREAD

**Issue by victbakk** [kartAI/NGIS-training-machine-webclient#228]

**Comment by victbakk** [comment]
Har sett på mulighetene for dette, tror jeg har kommet til en litt lett løsning for nettopp dette: uuid, som gir hver person en unik id. Har pushet dette opp til github, men har ikke funnet ut noe måte å teste dette på enda, jobber med saken.

**Comment by victbakk** [comment]
Pushet opp det jeg hadde, Cassandra finner tak i nåla og ser etter mulige problemer med fletting, totalt 4 timer brukt

**Comment by springvalley** [comment]
1 time brukt
