### ISSUE TITLE
FGB/COG Finne ut av ting

### ISSUE THREAD

**Issue by springvalley** [kartAI/NGIS-training-machine-webclient#280]

**Comment by springvalley** [comment]
Fjernet noen timer som går til oppgaven "Konvertere linjer til polygoner og fylle de inn"

**Comment by springvalley** [comment]
Fjernet 2 timer for oppgaven "Sy sammen COG med resten av applikasjonen"

**Comment by victbakk** [comment]
Fjernet 3 timer for "Lage fil som henter fra COG/azure"
