### ISSUE TITLE
Statusmøte

### ISSUE THREAD

**Issue by Thyrgils** [kartAI/NGIS-training-machine-webclient#320]

**Comment by Thyrgils** [comment]
Statusmøte onsdag 02. april

**Comment by victbakk** [comment]
30 min hver pers under diskusjon av oppstart og hva vi skal tenke på til tirsdag 2. april
Hvert medlem har fått tildelt et punkt der de skal tenke på frem til da, ligger i drive.

**Comment by victbakk** [comment]
Finito, tok tid, typ 47,5 t
