### ISSUE TITLE
Legge til markering for søm på map.html (åpent område)

### ISSUE THREAD

**Issue by LarisaSK** [kartAI/NGIS-training-machine-webclient#347]

**Comment by LarisaSK** [comment]
https://github.com/mmaciejkowalski/L.Highlight

**Comment by victbakk** [comment]
https://github.com/kartAI/NGIS-training-machine-webclient/pull/373
Pushet opp forsøk på leaflet highlight, men fikk det ikke til
Tror det er projeksjon som er problemet, ble bare frustrert av det

**Comment by springvalley** [comment]
Ferdig tok 30 min pluss den tiden Victor brukte
