### ISSUE TITLE
Finne ut av hvem som skal stå ansvarlig med kontaktpunkt for applikasjonen - GDPR (1 time)

### ISSUE THREAD

**Issue by victbakk** [kartAI/NGIS-training-machine-webclient#403]

**Comment by Thyrgils** [comment]
I personvernserklæringen skal det kalles en research preview.
Ansvarlig er KartAi-prosjektet.
Kontaktperson blir Alexander Salveson Nossum, alexander.nossum@norkart.no

Tok 1 time
