### ISSUE TITLE
Undersøke hvordan vi kan legge inn secrets i Azure og legge det til hvis mulig

### ISSUE THREAD

**Issue by springvalley** [kartAI/NGIS-training-machine-webclient#43]

**Comment by victbakk** [comment]
ayay captn

**Comment by victbakk** [comment]
Ser ut som det må settes og hentes fra et dedikert key vault:
https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-portal

**Comment by victbakk** [comment]
Denne er spesifikk for python https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python?tabs=azure-cli

**Comment by victbakk** [comment]
Undersøking tok 1 time ish, nå er det på implementeringen.

**Comment by victbakk** [comment]
Har skrevet koden så den skal i teorien hente direkte fra Azure hvis den er pusha opp i Azure. Hvis den feiler på å hente secrets derifra, så vil den prøvde å hente den lokalt, denne filen er delt med teamet gjennom sikre protokoller, kontakt meg hvis dere sliter med å finne den.

Den åpne delen av koden ligger på github under brancehen "testavnyenv"

Jeg ønsker ikke å pushe denne eller implemetere dette før vi har et funksjonalt prosjekt, for å unngå at den forutsaker feil, hvor den da er sålangt umulig å teste.
