### ISSUE TITLE
Kap. Valg, 8.3 flyttes til kap. 7 Utviklingsprosessen . men kun det om cookies, GDPR-flyttes til Refleksjon

### ISSUE THREAD

**Issue by Thyrgils** [kartAI/NGIS-training-machine-webclient#556]
Kap. Valg, 8.3 flyttes til kap. 7 Utviklingsprosessen . men kun det om cookies, GDPR-flyttes til Refleksjon

**Comment by springvalley** [comment]
Cookies er flyttet men ikke resten

**Comment by gsvartsund** [comment]
Flyttet til 4.1. Brukte 1 time
