### ISSUE TITLE
Se på gamle bachelorrapporter

### ISSUE THREAD

**Issue by Thyrgils** [kartAI/NGIS-training-machine-webclient#578]
Se på gamle bachelorrapporter (se Canvas og søk opp på UiA) og se om vi kan finne noe vi mangler, kan gjøre bedre eller rett og slett rappe)

**Comment by gsvartsund** [comment]
brukte 3 timer på å lese gjennom gamle rapporter.

**Comment by gsvartsund** [comment]
Brukte 3 timer på dette. Funn: https://docs.google.com/document/d/1MyHLm6KYIgphRr8SKdj9o9GZuoieiVxn-kkH9e3OGTw/edit
